// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdhymHnMglrG9wh-5R8tqN9--bTFdvOnM',
    appId: '1:930239192354:web:23e53dcd0a5ac3a46e197b',
    messagingSenderId: '930239192354',
    projectId: 'fir-flutter-codelab-da37e',
    authDomain: 'fir-flutter-codelab-da37e.firebaseapp.com',
    databaseURL: 'https://fir-flutter-codelab-da37e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-codelab-da37e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYtqCfq4xXxQSo7jqcG4pPVYKuprf3HvE',
    appId: '1:930239192354:android:3be9cb3b048e4b9a6e197b',
    messagingSenderId: '930239192354',
    projectId: 'fir-flutter-codelab-da37e',
    databaseURL: 'https://fir-flutter-codelab-da37e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-codelab-da37e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC2iJX0saiyQI1mnjGMorazF5oZ4Trc20',
    appId: '1:930239192354:ios:62f7f98fc40b22896e197b',
    messagingSenderId: '930239192354',
    projectId: 'fir-flutter-codelab-da37e',
    databaseURL: 'https://fir-flutter-codelab-da37e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-codelab-da37e.appspot.com',
    iosClientId: '930239192354-cslothpfjv9p4sqbfupa20m2h2mgcd15.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC2iJX0saiyQI1mnjGMorazF5oZ4Trc20',
    appId: '1:930239192354:ios:62f7f98fc40b22896e197b',
    messagingSenderId: '930239192354',
    projectId: 'fir-flutter-codelab-da37e',
    databaseURL: 'https://fir-flutter-codelab-da37e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fir-flutter-codelab-da37e.appspot.com',
    iosClientId: '930239192354-cslothpfjv9p4sqbfupa20m2h2mgcd15.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
